name: vibemine
version: '${version}'
main: io.rcw.vibemine.Vibemine
api-version: '1.21'
load: POSTWORLD
permissions:
  vibemine.vibe.start:
    default: true
  vibemine.vibe.continue:
    default: true
  vibemine.vibe.sessions:
    default: true
  vibemine.vibe.stop:
    default: true
  vibemine.vibe.plugins:
    default: op
  vibemine.vibe.plugins.enable:
    default: op
  vibemine.vibe.plugins.disable:
    default: op
  vibemine.vibe.plugins.delete:
    default: op
